build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8

style:
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: false
